---
sidebar: sidebar
permalink: task_dc_emc_powerstore.html
keywords: data collector, PowerStore, EMC, DELL
summary: Configuring DELL EMC PowerStore data collector.
---

= Dell EMC PowerStore data collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The EMC PowerStore data collector gathers inventory and performance information from EMC PowerStore storage. For configuration and performance, the data collector requires the floating IP address of cluster and credentials to commmunicate using REST API across HTTPS. Create one data collector per cluster, regardless if the cluster consists of 1, or as many as 4 appliances
 

== Terminology 

Cloud Insights acquires the following inventory information from this data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|host|host
|host_volume_mapping|host_volume_mapping
|hardware (it has Drives under "extra_details" object): Drives|Disk
|Appliance|StoragePool
|Cluster|Storage Array
|Node|StorageNode
|fc_port|Port
|volume|Volume
|InternalVolume|file_system
|===

Note: These are common terminology mappings only and might not represent every case for this data collector. 


== Requirements

The following information is required to configure this data collector:

* IP address or fully-qualified domain name of storage processor 
* Read-only user name and password 

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|PowerStore gateway(s)|IP addresses or fully-qualified domain names of PowerStore storage
|User Name|User name for PowerShare 
|Password|Password used for PowerShare 
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|HTTPS Port|Default is 443
|Inventory Poll Interval (minutes)|Interval between inventory polls. The default is 60 minutes.
|===

           
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].


